# Generated by Django 4.0.4 on 2022-04-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('or1', '0002_synth_delay_amount_synth_filter_amount_synth_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='synth',
            name='autowah_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='synth',
            name='distortion_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='synth',
            name='freeverb_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='synth',
            name='tremolo_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
            preserve_default=False,
        ),
    ]
